name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: viidhyanshu
          outputs: |
            ./pacman-contribution-graph.svg
            ./pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Generate Pacman Graph" || echo "No changes"
          git push
